Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'applications')
src	= Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]
CPPPATH += [cwd + '/../drv/display/uc1701/jlx128640/pump-one']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
